url:
  IP:
    original: "https://www.ehu.eus/ccwintco/uploads/2/22/Indian_pines.mat"
    corrected: "https://www.ehu.eus/ccwintco/uploads/6/67/Indian_pines_corrected.mat"
    ground_truth: "https://www.ehu.eus/ccwintco/uploads/c/c4/Indian_pines_gt.mat"
  KSC:
    original: "http://www.ehu.es/ccwintco/uploads/2/26/KSC.mat"
    ground_truth: "http://www.ehu.es/ccwintco/uploads/a/a6/KSC_gt.mat"
  PU:
    original: "https://www.ehu.eus/ccwintco/uploads/e/ee/PaviaU.mat"
    ground_truth: "https://www.ehu.eus/ccwintco/uploads/5/50/PaviaU_gt.mat"


